'''
python3 utils/create_database.py
'''
import sqlite3
import pandas as pd

# init
TABLE_NAME  = 'sinamicv20'

conn = sqlite3.connect('data/inverter.db')
c = conn.cursor()

c.execute(f"""
            CREATE TABLE {TABLE_NAME} (
            ID INT PRIMARY KEY,
            WDOG_TIME INT,
            WDOG_ACTION INT,
            FREQ_REF INT,
            RUN_ENABLE INT,
            CMD_FWD_REV INT,
            CMD_START INT,
            FAULT_ACK INT,
            PID_SETP_REF INT,
            ENABLE_PID INT,
            CURRENT_LMT INT,
            ACCEL_TIME INT,
            DECEL_TIME INT,
            DIGITAL_OUT_1 INT,
            DIGITAL_OUT_2 INT,
            REF_FREQ INT,
            PID_UP_LMT INT,
            PID_LO_LMT INT,
            P_GAIN INT,
            I_GAIN INT,
            D_GAIN INT,
            FEEDBK_GAIN INT,
            LOW_PASS INT,
            FREQ_OUTPUT INT,
            SPEED INT,
            CURRENT INT,
            TORQUE INT,
            ACTUAL_PWR INT,
            TOTAL_KWH INT,
            DC_BUS_VOLTS INT,
            REFERENCE INT,
            RATED_PWR INT,
            OUTPUT_VOLTS INT,
            FWD_REV INT,
            STOP_RUN INT,
            AT_MAX_FREQ INT,
            CONTROL_MODE INT,
            ENABLED INT,
            READY_TO_RUN INT,
            ANALOG_IN_1 INT,
            ANALOG_IN_2 INT,
            ANALOG_OUT_1 INT,
            FREQ_ACTUAL INT,
            PID_SETP_OUT INT,
            PID_OUTPUT INT,
            PID_FEEDBACK INT,
            DIGITAL_IN_1 INT,
            DIGITAL_IN_2 INT,
            DIGITAL_IN_3 INT,
            DIGITAL_IN_4 INT,
            FAULT INT,
            LAST_FAULT INT,
            FAULT_1 INT,
            FAULT_2 INT,
            FAULT_3 INT,
            WARNING INT,
            LAST_WARNING INT,
            INVERTER_VER INT,
            DRIVE_MODEL INT,
            STW INT,
            HSW INT,
            ZSW INT,
            HIW INT,
            INVERTER_MODEL INT,
            HAND_AUTO INT,
            FAULT_4 INT,
            FAULT_5 INT,
            FAULT_6 INT,
            FAULT_7 INT,
            FAULT_8 FLOAT,
            PRM_ERROR_CODE INT,
            PI_FEEDBACK INT);
        """)

c.execute(f"""
        INSERT INTO {TABLE_NAME} (
            ID,
            WDOG_TIME,
            WDOG_ACTION,
            FREQ_REF,
            RUN_ENABLE,
            CMD_FWD_REV,
            CMD_START,
            FAULT_ACK,
            PID_SETP_REF,
            ENABLE_PID,
            CURRENT_LMT,
            ACCEL_TIME,
            DECEL_TIME,
            DIGITAL_OUT_1,
            DIGITAL_OUT_2,
            REF_FREQ,
            PID_UP_LMT,
            PID_LO_LMT,
            P_GAIN,
            I_GAIN,
            D_GAIN,
            FEEDBK_GAIN,
            LOW_PASS,
            FREQ_OUTPUT,
            SPEED,
            CURRENT,
            TORQUE,
            ACTUAL_PWR,
            TOTAL_KWH,
            DC_BUS_VOLTS,
            REFERENCE,
            RATED_PWR,
            OUTPUT_VOLTS,
            FWD_REV,
            STOP_RUN,
            AT_MAX_FREQ,
            CONTROL_MODE,
            ENABLED,
            READY_TO_RUN,
            ANALOG_IN_1,
            ANALOG_IN_2,
            ANALOG_OUT_1,
            FREQ_ACTUAL,
            PID_SETP_OUT,
            PID_OUTPUT,
            PID_FEEDBACK,
            DIGITAL_IN_1,
            DIGITAL_IN_2,
            DIGITAL_IN_3,
            DIGITAL_IN_4,
            FAULT,
            LAST_FAULT,
            FAULT_1,
            FAULT_2,
            FAULT_3,
            WARNING,
            LAST_WARNING,
            INVERTER_VER,
            DRIVE_MODEL,
            STW,
            HSW,
            ZSW,
            HIW,
            INVERTER_MODEL,
            HAND_AUTO,
            FAULT_4,
            FAULT_5,
            FAULT_6,
            FAULT_7,
            FAULT_8,
            PRM_ERROR_CODE,
            PI_FEEDBACK)
            
        VALUES (0,0,0,0,0,0,0,999,0,1186,1000,1000,1,0,1500,10000,0,3000,0,0,10000,10000,
          0,0,0,0,0,17,315,7,55,0,1,0,0,1,1,0,0,21,0,0,999,0,0,0,0,0,0,0,0,0,0,0,0,0,394,
          6307,0,0,60209,0,6307,394,1,0,0,0,0,0.0,255,12);
          """)
conn.commit()

conn.close()